### ISSUE TITLE
Store offset causes wrong state error in kafka with confluent-kafka 2

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#365]
Store offset sometimes causes a wrong state error (-172) in the kafka input callack if auto store offsets is disabled and confluent-kafka 2 is used. This leads to crashes of the pipeline.
There are no errors with confluent-kafka 1.8.

More information can be found in the librdkafka changelog:
https://github.com/confluentinc/librdkafka/blob/master/CHANGELOG.md#upgrade-considerations-1

**Expected behavior**
Store offset shloud not cause any errors.

**Steps to reproduce**
Running logprep with a kafka input and auto store offset disabled causes this error sometimes once the batch is written.
It tends to happen in the beginning and stops happening at some point.

**Environment**

Logprep version: 078d68eb5c0963a21187505888c8bb8d38c8bf15
Python version: 3.11

**Comment by ekneg54** [comment]
as seen here (https://github.com/fkie-cad/Logprep/actions/runs/4893036487/jobs/8735509265?pr=381)  the donwgrade is not easy, because there are no packages for version 1.8.2 for python 3.11 so it has to be compiled during install which leads to install an external librdkafka which is not hold in all repositories. (we have no apt repositories in our build environment)

**Comment by ppcad** [comment]
Ok, maybe trying to fix it before the next release would be the way to go then.
