### ISSUE TITLE
Timestamper sets missing day to 01 and adds missing time as 00:00:00 - intentional?

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#610]
**Description**
If I pass the timestamper an incomplete timestamp (e.g. just the year and month - which is still valid ISO 8601, but incomplete), the processor automatically sets the day to `01` and the time to `00:00:00`. While I understand that we are aiming for a standardised output format when normalising, I think the current behaviour could cause problems in interpreting the resulting timestamp: Is the date really `2024-06-01`, or was the `01` automatically added and not in fact set in the source log? The same goes for the missing time – although admittedly the time `00:00:00` looks pretty auto-generated and is therefore less likely to be misinterpreted.

**Expected behavior**
If the day is missing in the source timestamp, the timestamper either gives a warning or only includes the year and month in the processed timestamp, without setting the missing day to `01`.

_Up for discussion:_ A missing time is not set automatically to `00:00:00`, but simply omitted (which would still be valid ISO 8601).

**Current behavior**
Note that the configuration is simplified to only include the relevant details.
```
{
    "inputDocument": {
        "year-month": "2024-12"
    },
    "processor_config": {
        "sourceField": "year-month",
        "targetField": "processed_timestamp",
        "sourceFormat": "ISO8601",
        "overwriteTarget": false
    },
    "outputDocument": {
        "year-month": "2024-12",
        "processed_timestamp": "2024-12-01T00:00:00Z"
    }
}
```
Logprep version: 11.3.0

**Comment by ekneg54** [comment]
@gigallucci could you explain if we have constrains considering opensearch templates?

**Comment by ekneg54** [comment]
In my opinion no log should be processed with missing days or times. So an error should be the correct reaction for both cases.

**Comment by gigallucci** [comment]
> @gigallucci could you explain if we have constrains considering opensearch templates?

A date in OpenSearch can be represented as one of the following:

- A long value that corresponds to milliseconds since the epoch (the value must be non-negative). Dates are stored in this form internally.
- A formatted string.
- An integer value that corresponds to seconds since the epoch (the value must be non-negative).

Default format is: `strict_date_time_no_millis||strict_date_optional_time||epoch_millis`.

For more details see  [date](https://opensearch.org/docs/2.14/field-types/supported-field-types/date)

**Data-Stream:**
Every document indexed to a data stream must contain a timestamp field - default is @timestamp - mapped as a [date](https://opensearch.org/docs/2.14/field-types/supported-field-types/date)  field type. If the index template doesn’t specify a mapping for the timestamp field, Opensearch maps @timestamp as a date field with default options.

So yes, it is valid to set only a date without a timestamp. If there is no timestamp in the document or an invalid date, opensearch throws an error. 

**Index:**
An index does not need a timestamp, but when defined, the  timestamp must be provided in the given format.
