### ISSUE TITLE
No support for the mysql-connector-python library in version 9.0.0

### ISSUE THREAD

**Issue by dtrai2** [fkie-cad/Logprep#629]
When using `mysql-connector-python` in version `9.0.0` logprep is not able to run.

**Expected behavior**
Logprep runs normally.

**Current behavior**
A stacktrace is printed during the text execution:

```bash
tests/acceptance/test_wineventlog_pseudonymization.py:7: in <module>
    from logprep.util.configuration import Configuration
logprep/util/configuration.py:220: in <module>
    from logprep.factory import Factory
logprep/factory.py:6: in <module>
    from logprep.configuration import Configuration
logprep/configuration.py:6: in <module>
    from logprep.registry import Registry
logprep/registry.py:30: in <module>
    from logprep.processor.generic_adder.processor import GenericAdder
logprep/processor/generic_adder/processor.py:50: in <module>
    from logprep.processor.generic_adder.mysql_connector import MySQLConnector
logprep/processor/generic_adder/mysql_connector.py:13: in <module>
    class MySQLConnector:
logprep/processor/generic_adder/mysql_connector.py:36: in MySQLConnector
    _cursor: mysql.connector.connection.CursorBase
E   AttributeError: module 'mysql.connector.connection' has no attribute 'CursorBase'
```

**Steps to reproduce**
Create a new venv with  `mysql-connector-python` in version `9.0.0` and run the logprep tests

**Environment**
Logprep version: main
Python version: 3.11

**Comment by ekneg54** [comment]
we should extract this dependency and functionality from logprep. with the provided getter mechanic in combination with the reload_interval it is easy to provide this in an external API. It should't be the responsibility of logprep to provide a database interface for MySQL in the generic_resolver, because if we start with MySQL we have to provide support for all other databases too. That can't be our intention.
