### ISSUE TITLE
CI complains hitting rate limit on trivy scan

### ISSUE THREAD

**Issue by ekneg54** [fkie-cad/Logprep#700]
**Expected behavior**
the CI Containerbuilds should complete with trivy scan

**Current behavior**
sometimes they does not complete because of a rate limit.
this behavior is a known "bug" ... see: https://github.com/aquasecurity/trivy/discussions/7668

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/d8228301-cbca-40ed-9ab4-25aeb6982902">

**Steps to reproduce**
* run ci pipeline frequently

**Possible solution**

* cache trivy db for 1 day in the pipeline to reduce requests

**Comment by ekneg54** [comment]
@P4sca1 could you have a look on that?

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the .github/workflows/ci.yml file to cache the Trivy DB for one day, reducing the number of requests and mitigating the rate limit issue.

I also created pull request: https://github.com/fkie-cad/Logprep/pull/701


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by P4sca1** [comment]
There is a Trivy PR which aims to solve this issue by providing additional fallback registries.

In the meantime, the following workaround might help: https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-10884984.

**Comment by ekneg54** [comment]
not fixable here
